language: node_js
node_js:
- '4'
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: lXEJrvILQ34ZmxwDwIoN3QxuIKRG3/3ZoPhQ7ou0KTVfoPuvkMlFmUj50i5u+Hl5xw11KdHHHukvWurBMPBS1UBWFD3zuotRkw7awHk6iJgA1HPpl6ZxvMwIv/jIP/9vLJo7DD2Z2gkWrMUsQaHx9VpAdOEa8UHo3hsq2nc7P6eQVnJXrJUKA41G1HiRiwmPp+RQ/KuAL14H0+5UAJLZhsG6ikonvS1VCTrbpWV/jjOo9vYLc/SARHHxBhP5WknjRkVR71guopx+L5tnHzY+nWydwUVuVk0og7GLpjzlxrfukGepuAcx5aRFxK7JURwII/oNAUb+8kZ9dnYt2/58XSLB3LR29TYbU/iJ4rsQloBaK4fGqsUsoBdF5Jt6DgcFzKtRv3Tk3Vu1WVmmNIn7TUtP9tYItC7uXWbvN1UpX+m8TUSileDCV+FdHQ3NI2VwNp0xdo4Md4ElzSH/0TXc0FgQlsnI8O8wwkmyURwjj3Tcc4mjIkWL+sp2FP7aU/jrhCW5Ftkse1wwmdsigoHaa9heHXcDMJFy6AfJi9t2vs0VbUkaGZgEY+JU7YIk0U9Z1Z5k6Ao/2SJnu3CM9YRf6/2T81NB5+E8tbWgR+Cbqfivf6TUe47wElWvVXdtYWtl9e1q6xnxg5WBthkixVC0/1rW3qXjyOmGqBc5QmgrG4g=
  app: tftrocks
  on:
    repo: jacgrady1/F_web
